### PR TITLE
Fix: increase speed export

### LINKED ISSUE #112: Price CollectionDecorator retrieves all products multiple times
Hi,

We ran into an issue where the export was very slow due to a large product and eav_attributes dataset. The main problem we've found is in the price collection decorator. 

The diff below show the change I made to fix the problem. Instead of creating a whole new ProductCollection each iteration, we create one before the loop that only contains products that are also in the parameterized PriceCollection.

```diff
--- a/vendor/tweakwise/magento2-tweakwise-export/Model/Write/Products/CollectionDecorator/Price.php	
+++ b/vendor/tweakwise/magento2-tweakwise-export/Model/Write/Products/CollectionDecorator/Price.php
@@ -74,7 +74,7 @@
         $websiteId = $collection->getStore()->getWebsiteId();
 
         $priceSelect = $this->createPriceSelect($collection->getIds(), $websiteId);
-        $priceQuery = $priceSelect->getSelect()->query();
+        $priceQueryResult = $priceSelect->getSelect()->query()->fetchAll();
 
         $currency = $collection->getStore()->getCurrentCurrency();
         if ($collection->getStore()->getCurrentCurrencyRate() > 0.00001) {
@@ -85,12 +85,15 @@
 
         $priceFields = $this->config->getPriceFields($collection->getStore()->getId());
 
-        while ($row = $priceQuery->fetch()) {
+        $priceProductIds = array_column($priceQueryResult, 'entity_id');
+        $productCollection = $this->collectionFactory->create()->addFieldToFilter('entity_id', ['in' => $priceProductIds]);
+
+        foreach ($priceQueryResult as $row) {
             $entityId = $row['entity_id'];
             $row['currency'] = $currency->getCurrencyCode();
             $row['price'] = $this->getPriceValue($row, $priceFields);
 
-            $product = $this->collectionFactory->create()->getItemById($entityId);
+            $product = $productCollection->getItemById($entityId);
             $taxClassId = $this->getTaxClassId($collection->get($entityId));
 
             if ($this->config->calculateCombinedPrices($store) && $this->isGroupedProduct($product)) {

```

### PR DESCRIPTION
**Pull request by ahuininga-orisha**
This pull request improves export performance significantly—by about 86% on smaller databases, with even greater gains observed on larger datasets. While the memory usage of the price decorator increases, the overall memory consumption decreases by roughly 5.7%.

@rtgschepers After further testing on a smaller database, I can confirm that although the price decorator uses more memory, the total memory footprint is reduced.

Fixes #112

### CODE REVIEW

File: Model/Write/Products/CollectionDecorator/Price.php [hunk 1]
```diff
@@ -83,14 +83,20 @@ public function decorate(Collection|PriceCollection $collection): void
 
         $this->exchangeRate = $exchangeRate ?? 1.0;
 
-        $priceFields = $this->config->getPriceFields($collection->getStore()->getId());
+        $priceFields       = $this->config->getPriceFields($collection->getStore()->getId());
+        $priceProductIds   = array_column($priceQueryResult, 'entity_id');
```
Comment (jansentjeu) [inline Model/Write/Products/CollectionDecorator/Price.php]: Remove unnecessary spaces

File: Model/Write/Products/CollectionDecorator/Price.php [hunk 2]
```diff
@@ -83,14 +83,20 @@ public function decorate(Collection|PriceCollection $collection): void
...
+        $productCollection = $this->collectionFactory->create()
+            ->addFieldToFilter(
+                'entity_id',
+                ['in' => $priceProductIds]
+            );
 
-        while ($row = $priceQuery->fetch()) {
-            $entityId = $row['entity_id'];
+        foreach ($priceQueryResult as $row) {
+            $entityId        = $row['entity_id'];
```
Comment (jansentjeu) [inline Model/Write/Products/CollectionDecorator/Price.php]: Remove unnecessary spaces

File: Model/Write/Products/CollectionDecorator/Price.php [hunk 3]
```diff
@@ -83,14 +83,20 @@ public function decorate(Collection|PriceCollection $collection): void
...
             $row['currency'] = $currency->getCurrencyCode();
             $row['price'] = $this->getPriceValue($row, $priceFields);
 
-            $product = $this->collectionFactory->create()->getItemById($entityId);
+            $product    = $productCollection->getItemById($entityId);
```
Comment (jansentjeu) [inline Model/Write/Products/CollectionDecorator/Price.php]: Remove unnecessary spaces

**Review by jansentjeu — CHANGES_REQUESTED** [review]

**Review by jansentjeu — APPROVED** [review]
